"use client";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { InvitationThemeCard } from "@/components/dashboard/invitation-theme-card";
import { deleteInvitation,duplicateInvitation,setInvitationPublished,updateInvitation } from "@/lib/actions/invitations";
import { normalizeSlug } from "@/lib/validation/invitation"; import { Copy,Loader2,Save,Trash2 } from "lucide-react"; import { useRouter } from "next/navigation"; import { useState } from "react"; import { toast } from "sonner";
type Theme={id:string;name:string;slug:string;description:string|null;category:string;features:unknown;price:number;is_premium:boolean}; type Invitation={id:string;theme_id:string|null;slug:string;status:string;is_published:boolean};
export function EditInvitationForm({invitation,themes}:{invitation:Invitation;themes:Theme[]}) {
 const [themeId,setThemeId]=useState(invitation.theme_id??""); const [slug,setSlug]=useState(invitation.slug); const [saving,setSaving]=useState(false); const router=useRouter();
 async function save(){setSaving(true);try{const result=await updateInvitation(invitation.id,{themeId,groomName:"Nama Mempelai Pria",brideName:"Nama Mempelai Wanita",slug:normalizeSlug(slug)});if(result.error){toast.error(result.error);return;}toast.success("Pengaturan tersimpan.");router.refresh();}finally{setSaving(false);}}
 async function remove(){if(!window.confirm("Hapus undangan ini? Tindakan ini tidak dapat dibatalkan."))return;setSaving(true);try{const result=await deleteInvitation(invitation.id);if(result.error){toast.error(result.error);return;}router.push("/dashboard/invitations");}finally{setSaving(false);}}
 async function duplicate(){setSaving(true);try{const result=await duplicateInvitation(invitation.id);if(result.error){toast.error(result.error);return;}if(result.id)router.push(`/dashboard/invitations/${result.id}`);}finally{setSaving(false);}}
 async function togglePublish(){setSaving(true);try{const result=await setInvitationPublished(invitation.id,!invitation.is_published);if(result.error){toast.error(result.error);return;}toast.success(invitation.is_published?"Undipublish.":"Dipublish.");router.refresh();}finally{setSaving(false);}}
 return <div className="space-y-6"><Card><CardHeader><CardTitle>Lifecycle</CardTitle><CardDescription>Status sekarang: {invitation.status}</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button onClick={togglePublish} disabled={saving}>{saving&&<Loader2 className="size-4 animate-spin"/>}{invitation.is_published?"Unpublish":"Publish"}</Button><Button variant="outline" onClick={duplicate} disabled={saving}><Copy className="size-4"/>Duplikat</Button><Button variant="destructive" onClick={remove} disabled={saving}><Trash2 className="size-4"/>Hapus</Button></CardContent></Card><Card><CardHeader><CardTitle>Tema aktif</CardTitle><CardDescription>Memilih tema mengganti struktur section draft dengan definisi tema tersebut.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{themes.map(theme=><InvitationThemeCard key={theme.id} theme={theme} selected={themeId===theme.id} onSelect={()=>setThemeId(theme.id)}/>)}</CardContent></Card><Card><CardHeader><CardTitle>Pengaturan dasar</CardTitle><CardDescription>Slug publik harus stabil setelah dibagikan.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="slug">Slug</Label><Input id="slug" value={slug} onChange={e=>setSlug(e.target.value)} maxLength={80}/></div><Button onClick={save} disabled={saving||!themeId||!slug.trim()}>{saving?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Simpan</Button></CardContent></Card></div>;
}